In [23]:
import os
from glob import glob
import pandas as pd
import numpy as np

file_path = (
    r"C:\Users\sjdal\Github\smTIRF\ML_Pipeline\Traj_67pM-GRP1_ND08_01_preprocessed_data_01.xlsx"
)
one = pd.read_excel(file_path)

file_dir = r"C:\Users\sjdal\Github\smTIRF\ML_Pipeline"
files = os.path.join(file_dir, "*.xlsx")
g = glob(files)
df = pd.concat(map(pd.read_excel, g), ignore_index=True)

C:\Users\sjdal\Github\smTIRF\ML_Pipeline\*.xlsx


In [24]:
df= df.drop_duplicates().reset_index(drop=True)

In [25]:
keep = df[df["Average_Brightness"].between(3.3, 3.5)]
keep = keep[keep["Length (frames)"] > 10]
keep = keep[keep["MSD"].between(0.25, 3.5)].assign(Keep=1)
all = pd.merge(df, keep, how="left").fillna(0)[["Average_Brightness", "Length (frames)", "MSD", "Keep"]]

Index(['Average_Brightness', 'Length (frames)', 'MSD', 'Keep'], dtype='object')


In [26]:
parameters = all.iloc[:, :-1]
identities = all.iloc[:, -1]

all_arr = all.to_numpy()
inputs = parameters.to_numpy()
outputs = identities.to_numpy()

In [30]:
indeces_permutation = np.random.permutation(len(all_arr))
shuffled_inputs = inputs[indeces_permutation]
shuffled_targets = outputs[indeces_permutation]

num_validation_samples = int(0.3 * len(inputs))
val_inputs = shuffled_inputs[:num_validation_samples]
val_targets = shuffled_targets[:num_validation_samples]
training_inputs = shuffled_inputs[num_validation_samples:]
training_targets = shuffled_targets[num_validation_samples:]

[[  2.81024242  66.           1.01934398]
 [  3.51636082  97.           1.67416377]
 [  3.17316667   6.           0.37862829]
 ...
 [  3.33779817 109.           1.9387675 ]
 [  3.29143653 323.           1.62340997]
 [  3.44724057 212.           1.57082131]]
